version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - cd frontend
      - npm install
      - cd ../backend
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - cd ../frontend
      - npm run build
      - cd ../backend
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: 'backend'